## What is `datelife`?

`datelife` is an R package that allows researchers and the general audience to obtain
open scientific data on the age of any organism they are interested in, by retrieving
organism ages from a database of dated phylogenetic trees (_aka_ chronograms), that
have been peer-reviewed and published as part of a scientific research
article, in an indexed journal ([Open Tree of Life's tree store](https://tree.opentreeoflife.org/curator)).
As such, organism ages retrieved by `datelife` constitute state-of-the-art,
peer-reviewed, public scientific knowledge, that can be accessed and reused by
experts and non-experts in the field alike.

## How can you use `datelife`?

You can install the `datelife` R package on your own computer and use it locally.
You can find instructions for a local installation below.

If you do not want/have time to deal with installation and R code, you can use
[DateLife's interactive website application](`r ifelse(website_down, "https://github.com/phylotastic/datelifedocker", "http://datelife.opentreeoflife.org/query/")`). `r if (website_down) "Note that the website is not live at the moment, apologies."`

<!-- http://datelife.opentreeoflife.org/query/ -->
