<html>
<?php include("pagestart.html"); ?>
<h2>FAQ</h2>
<br />
<p><b>What can I do with <a href="http://datelife.org">DateLife</a>?</b></p>
<p>You can interact with it as a website to get estimates for the ages of various groups. You can also run automated queries against it. While still in alpha form, the api may change, but you can see what it is at any point by just looking at the URL. For example, searching for a Newick tree for three particular taxa, using only peer-reviewed studies, sends you to this page:
<br /><code><a href="http://datelife.org/cgi-bin/R/result?taxa=Rhinoceros_unicornis%2CEquus_caballus%2CMus_musculus&format=newickmed&partial=liberal&useembargoed=no&uncertainty=100">http://datelife.org/cgi-bin/R/result?taxa=Rhinoceros_unicornis%2CEquus_caballus%2CMus_musculus&format=newickmed&partial=liberal&useembargoed=no&uncertainty=100</a></code>
<br />You could have a python, perl, or R script call this same URL to get trees back. By changing <code>format=newickmed</code> to <code>format=bestguess</code> you get a single point estimate of the age of the MRCA of the group of taxa, which can be used by other scripts. It's fine to use automated tools to query the site, we just ask that you try not to hit it so frequently as to degrade performance for others (perhaps give it a few seconds between calls, schedule hard use for the middle of the night, etc.). We haven't yet tested at what usage frequency it stops working well. You can download the source code and run it locally, perhaps hacking it for some other purpose. If you reuse in that way, we'd appreciate being cited (citation being the currency of science). If you have an improvement to make, either send us a patch or sign up as a developer (though forking the code is also possible, of course). The main code is R, which is fairly easy to use. We're planning to turn much of the code into an open source standalone R package as well (while also keeping the rest open).</p>
<p><b>Can I watch a movie about it?</b></p>
<p>Here is a presentation we gave at iEvoBio in July, 2012:
<br /><iframe width="420" height="315" src="http://www.youtube.com/embed/xWmLrbUWtyM?rel=0" frameborder="0" allowfullscreen></iframe>
</p>
<p><b>What is next?</b></p>
<p>Over the 2012 summer, we will be adding taxonomic name resolution, many more taxa besides mammals, adding a service for you to upload a phylogram and get back a chronogram, and other goodies. Note that the project only started on June 4, 2012, so development is still very active. Stay tuned!</p>
<p><b>What do I cite?</b></p>
<p>First, the papers for the trees and fossils you are using, if possible. It is like citing papers contributing data to GenBank: if you were to analyze one or two datasets, you would cite the papers that generated them; if you were to analyze all the plant rbcl sequences in GenBank, you might not. We also ask that you cite our website (we hope to have a peer-reviewed publication soon to cite instead).</p>
<p><b>Who is "we"?</b></p>
<p>Currently, Brian O'Meara, Luke Harmon, Jonathan Eastman, Peter Midford, Tracy Heath, Joseph Brown, Matt Pennell, Mike Alfaro. Maybe you, too?</p>
<p><b>Who paid for this?</b></p>
<p><a href="http://datelife.org">DateLife</a> was developed as part of the <a href="http://phylotastic.org/">Phylotastic</a> hackathon, sponsored by <a href="http://www.nescent.org">NESCent</a>, <a href="http://www.iplantcollaborative.org/">iPlant</a>, and <a href="http://synthesis.eol.org/">BioSynC</a>. <a href="http://www.nescent.org">NESCent</a> is funded by  the National Science Foundation (Grant #EF-0905606) and <a href="https://www.gifts.duke.edu/nescent">your donations</a>. <a href="http://www.iplantcollaborative.org/">iPlant</a> is funded by a grant from the National Science Foundation Plant Cyberinfrastructure Program (#DBI-0735191). <a href="http://synthesis.eol.org/">BioSynC</a> is funded by the MacArthur Foundation as well as the National Science Foundation, The J.B. and M.K. Pritzker Family Foundation, The Harris Family foundation and MaryEllen and Richard Keyser, and many more donors. The computing infrastructure behind <a href="http://datelife.org">DateLife</a> was funded by startup funds from the <a href="http://www.utk.edu">U. of Tennessee, Knoxville</a> for <a href="http://www.brianomeara.info">Brian O'Meara</a>.</p>
<p><b>Don't you know about <a href="http://www.timetree.org">TimeTree</a>? Why do a new site?</b></p>
<p><a href="http://www.timetree.org"a>TimeTree</a> (Hedges et al., 2006 [<a href="http://kumarlab.net/pdf_new/HedgesKumar06.pdf">PDF</a>]) is a good resource for date information. It has expert-derived dates as well as dates from published trees. It also has a good web interface (for mobile devices, too) and now free <a href="http://itunes.apple.com/us/app/timetree/id372842500?mt=8">iPhone</a> and <a href="http://itunes.apple.com/us/app/timetree-hd/id468820058?mt=8">iPad</a> apps. You can even get free book chapters and poster images or buy a physical book or poster. These are all remarkable tools for outreach and for answering targeted questions. What you may not do is reuse the data in an automated manner (at least when we started our project in June 2012). For example, <a href="http://www.timetree.org"a>TimeTree</a> displays this note (as of June 8, 2012):
<br /><center><img src="images/timetreereuse.png"></center>
<br />and the FAQ states (as of June 8, 2012):
<br /><center><img src="images/timetreedownload.png"></center></p>
<p>Requests to allow download of the calibrated tree or other widespread reuse have been consistently but politely declined. Reusing existing work makes a great deal of sense, but since this was not possible, we decided to develop our own. It differs from <a href="http://www.timetree.org"a>TimeTree</a> in other ways that we hope are improvements, such as allowing for information about uncertainty from individual studies, but the prohibition on large-scale reuse was really the key issue driving our development.</p>
<p><b>Who is <a href="http://www.nodethirtythree.com/">NodeThirtyThree Design</a>?</b></p>
<p>We have no idea. They make free web design templates with generous reuse licensing but ask for people to cite them. So we have.</p>
<?php include("pageend.html"); ?>
