citations<-c()
embargoed<-c()
studies<-list()
original.wd<-getcwd()
setwd("/Library/WebServer/Sites/datelife.org/datelife/data/")
print(system("ls",intern=TRUE))

print("beginning to load data")

citations<-append(citations,"Bininda-Emonds et al. 2007")
embargoed<-append(embargoed,FALSE)
load("bininda.emonds.rda")
studies<-append(studies,bininda.emonds.all)
print(citations)
print(ls())

citations<-append(citations,"10K trees Carnivores, V1")
embargoed<-append(embargoed,FALSE)
load("harvard10k.carnivores.rda")
studies<-append(studies,harvard10k.carnivores.all)
print(citations)
print(ls())

citations<-append(citations,"10K trees Perissodactyla, V1")
embargoed<-append(embargoed,FALSE)
load("harvard10k.perissodactyla.rda")
studies<-append(studies,harvard10k.perissodactyla.all)
print(citations)
print(ls())

citations<-append(citations,"10K trees Primates, V3")
embargoed<-append(embargoed,FALSE)
load("harvard10k.primates.rda")
studies<-append(studies,harvard10k.primates.all)
print(citations)
print(ls())

citations<-append(citations,"Heath et al. 2012")
embargoed<-append(embargoed,FALSE)
load("heath.rda")
studies<-append(studies,heath.all)
print(citations)
print(ls())
setwd(original.wd)